### PR TITLE
Update Ansible playbook

### PR DESCRIPTION
**Pull request by hos7ein**
This pull request include below changes:

- Update python packages for CentOS distribution

- Update binary path in systemd file for haproxystats-pull service

- Update binary path in systemd file for haproxystats-process service

### CODE REVIEW

**Comment by unixsurfer** [comment]
Why do we change the **bindir** from `/usr/bin` to `/usr/local/bin`?
@hos7ein Thanks a lot for keeping the Ansible playbook up to date. Your work is very much appreciated.

**Comment by hos7ein** [comment]
Your welcome. 

Because:
-  `/usr/bin` is for distribution-managed normal user programs.
- `/usr/local/bin` is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into `/usr/bin` because future distribution upgrades may modify or delete them without warning.
And also, this command can be executed for more information:
`$man hier`
Or this links:
https://linux.die.net/man/7/hier
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure

**Comment by unixsurfer** [comment]
@hos7ein thanks for the detailed explanation.

**Comment by unixsurfer** [comment]
Do you want me to issue a new release ?

**Comment by hos7ein** [comment]
No it's not necessary, because I update Ansible playbook based on your release.

**Pull request merged**
